name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Install dependencies'
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: client/pnpm-lock.yaml

      - name: 'Install frontend dependencies'
        run: cd client && pnpm install

      - name: 'Run linter'
        run: cd client && pnpm run lint

  server:
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_DB: ranger-testdb
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Install dependencies'
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: server/pnpm-lock.yaml

      - name: 'Install backend dependencies'
        run: cd server && pnpm install

      - name: 'Install 7zip'
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: 'Run migrations'
        run: |
          cd server
          pnpm run test:db:migrate
          pnpm run test:db:seed
        env:
          DB_TEST_HOST: localhost
          DB_TEST_USER: postgres
          DB_TEST_NAME: ranger-testdb
          DB_TEST_PORT: 5432
          DB_TEST_PASSWORD: pass
          NODE_ENV: test

      - name: 'Run tests'
        run: |
          cd server
          pnpm run test 
        env:
          DB_TEST_HOST: localhost
          DB_TEST_USER: postgres
          DB_TEST_NAME: ranger-testdb
          DB_TEST_PORT: 5432
          DB_TEST_PASSWORD: pass
          NODE_ENV: test
